---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: "postgres"
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres:11
        env:
        - name: POSTGRES_DB
          value: sahana
        - name: POSTGRES_USER
          value: sahana
        - name: POSTGRES_PASSWORD
          value: password
        - name: PG_DATA
          value: /var/lib/postgres/data/pgdata
        ports:
        - containerPort: 5432
          name: mysql
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgres/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi
